### ISSUE TITLE
play stream urls in video player of user choice

### ISSUE THREAD

**Issue by moWerk** [zwieberl/harbour-fishtheke#9]
It would be really cool if one could define a video player in settings to feed the stream urls into when clicked instead of "just" copying the link to clipboard.

**Comment by zwieberl** [comment]
Yes, completely agree. 
Unfortunately, this is probably hard to do, as each player requires the URL to be given in a very specific way (most with differently named commandline options, some only after startup with dbus, some probably with GUI only).
Not quite sure how to pull that off in a generic way

**Comment by moWerk** [comment]
maybe focus on LLs Videoplayer. 
It is by far the most distributed and reliable player for sfos and Leszek is easy to approach and helpful if you might run into any issues.

**Comment by jgibbon** [comment]
I see multiple ways to do this, which may or may not be combined. Many are already mentioned by @zwieberl, but I am going to ramble on about them, anyway, because some points may be helpful to reach a decision, who knows. 

- _Nemo Transfer Engine_ seems to be the "official" (in quotes because I don't think services are accepted in harbour) way to "share" urls with other applications/services. The main problem being missing integration almost everywhere. **I don't think it is a viable solution** because of this.
- _Manual/hard coded integration_ of executables like LLs Videoplayer. These would have to check if the binary exists and have some kind of "argument template" if it's expected to be extendable to other players (or possibly download managers/wget/…?) in the future. 
  - In case of LLs, it's just `harbour-videoPlayer "[URL]"` (including quotes), the executable to check for this is `/usr/bin/harbour-videoPlayer`. I'd guess this wouldn't be hard, but I am not aware of other Players able to do this. Stock media player, pico player and the ancient Kodi port (it segfaults with a uri argument) do not.
- _Mpris "openUri"_ for a **currently running** player. This would requiring to check if a player is currently active and if it's claiming to be able to open URIs, then getting the active Player Name(s) to display it. That sounds like a lot of work, but would enable playing via apps like kodimote. (I have not tested OpenUri on it, but [it's there](https://github.com/accumulator/kodimote/blob/be014cc56fb01cdd71aaaa77888b26c77a8391bb/libkodimote/mpris2/mprisplayer.cpp#L303)). The stock Jolla media player (I'd guess the real "most distributed") claims to be able to open "file,http,https" via mpris/dbus (I checked with the "visual d-bus" application: Dbus com.jolla.mediaplayer → /org/mpris/MediaPlayer2/ → org.mpris.MediaPlayer2 → SupportedUriSchemes() ). 
  - Perhaps this could be somehow combined with the "run application manually" way, but I don't think there's a good way to ensure that the application is loaded (and, in the case of things like kodimote: connected). So, **not really worth the possibly huge effort**, IMHO.
- _xdg-open_: While far from optimal, I think it **really is the easiest way**. It opens the URL in the standard browser, which can most likely at least play the video, even if it's not the prettiest interface for doing so. If the user has WebCat set as the default browser, there's a setting "use external video player" – which really just means "use LLs Video player if installed".

cheers!

**Comment by zwieberl** [comment]
Wow, thank you so much for this! 
I was also thinking about manual integration and was dimly aware of the potential problem of "is the application already running or not?". 

About your last point: There seems to be another (quicker) way to do, what _xdg-open_  does: `Qt.openUrlExternally(url)` in QML. I implemented this in one of my last commits. It opens the sailfish-browser. I assume, if another one is configured to be the default-browser that one will be opened instead. 

We might ask ask LL for additionall input (if you haven't already), if he knows of any other way at least in his code. 

But I'm afraid that due to the mentioned problems, we can only go for "copy to clipboard" or "open in browser" (which will be there for the next release)

**Comment by jgibbon** [comment]
Oh of course. `Qt.openUrlExternally` escaped my mind there for a bit. It even calls xdg-open in the background, AFAIK, and is obviously even easier since it's available in QML. Good catch.

I haven't asked LL but have read most of WebCats sources in the past to prepare for a thing I contributed there. The player not so much, I've just skimmed about in it. In the current code base there doesn't seem to be much more one could do.
But the main thing that's potentially irritating with the current plan (assuming WebCat and videoPlayer to be installed and videoPlayer to be configured in WebCat) is that WebCat will stay open with an empty tab. I guess a change in WebCat to close the current tab when opening the external videoPlayer if the tab's history is empty would be not very hard and may just be accepted. Opening the video would take a bit longer because of the detour, but I think that's bearable for a "one-liner" solution on this side.

cheers!

**Comment by zwieberl** [comment]
Tried the jolla media player with D-Bus / Mpris:
It only supports wav-audio. But sending an URL pointing to a wav-file (http://techslides.com/sample-files-for-development) to it via "Visual D-Bus" does play it. 

I'm not quite sure at the moment if we can discover all services that offer "openUri" via D-Bus. If we could, we might query ilve which services are open at the moment and only display those as send-options.
(Although it did open the closed media-player, if I utilize openUri(). But then we would need to know and remember the exakt dbus-address, i.e. hard-code it)

The idea would be to "force" (== kindly ask) other projects to open a dbus-channel if they want to be able to receive URLs.

**Comment by fuchsmich** [comment]
Just wanted to throw in that my [idea](https://github.com/llelectronics/videoPlayer/issues/27) was to integrate mediathekview into LLs player and he pointed me to this project. So he's aware of it.

**Comment by zwieberl** [comment]
Sooo, Jollas stock gallery has `playVideoStream()` (which works), jupii (Upnp-app that was asked for in the comments) has `addUrl()` (not tested), Jollas stock media player (audio) has `OpenUri()`, all under different paths and LLs VideoPlayer has no dbus-interface at all.

So much for consistency. 
I think the only reasonable choice would be to hardcode the possible apps to send the URL to, scan live which are currently available, and display them as options. This would only work for already opened apps. One can start an app by dbus, but then we would need to know if its installed or not. 

Any thoughts?

Edit: Got "Open in Gallery" implemented very quickly in QML. But I haven't found an easy way to check, whether an app like jupii is installed or not.

**Comment by jgibbon** [comment]
With a hardcoded list of applications, everything you've mentioned should be possible… but checking for file existence does require C++ or Python. [Here's how Webcat does it for one file](https://github.com/llelectronics/webcat/blob/4fd3960eff3aa55189c6f621748863ebf3a5e19e/src/harbour-webcat.cpp#L234). Starting a process does too, obviously. ([webcat src](https://github.com/llelectronics/webcat/blob/4fd3960eff3aa55189c6f621748863ebf3a5e19e/src/myclass.cpp#L121))

One could even default to "execute commands" to keep things comparably simple implementation-wise, because that command could just be a "dbus-send" (or a list of commands, see download example below). In my head the **js-pseudocode** list model looks something like this:
```
commandmodel = [{
 displayName: qsTr('LLs Video Player'),
 fileToCheck: '/usr/bin/harbour-videoPlayer',
 execute: '/usr/bin/harbour-videoPlayer -p "%1"'
},{
 displayName: qsTr('Jolla Gallery'),
 fileToCheck: '/usr/bin/jolla-gallery',
 execute: 'dbus-send --dest=com.jolla.gallery --print-reply /com/jolla/gallery/ui com.jolla.gallery.ui.playVideoStream array:string:"$1"'
},{
 displayName: qsTr('Download in Terminal'),
 fileToCheck: '/usr/bin/fingerterm',
 execute: 'fingerterm -e "curl -o /home/nemo/Videos/$2.mp4 \"$1\" ;echo 'finished. press key to close';read -n1"'
},
//…
];
```

Of course, the /home/nemo path should not be hardcoded (harbour restriction) as well, this is all just for demonstration and "thinking out loud" purposes… 
Further steps: The list should be iterated, I guess, on application start, to fill a QML list model with the available commands. Additionally to the "check file existence" method, the "launch command" method has to be implemented in C++ and exported to QML.

cheers!

**Comment by zwieberl** [comment]
We now have 6 different options for handling the URL. I think this is enough for now and will close this issue.
If any new target-app arises, we can make an individual issue for that one.

**Comment by moWerk** [comment]
Great work!
